# Data Structures

## Array
Definition: _A collection of data elements identified by index or key._
- Calculate item index: **O(1)**
- Insert or delete item at beginning: **O(N)**
- Insert or delete item in middle: **O(n)**
- Insert or delete item at end: **O(1)**

In [49]:
import numpy as np

# Array with one dimension
array1 = [1, 2, 4, 8, 16]
print("One-dimensional array:", str(array1))

# Array with two dimensions
array2 = [[1, 2, 3, 4], [2, 4, 6, 8], [4, 8, 12, 16], [8, 16, 24, 32]]
matrix = np.matrix(array2)
print("Two-dimensional array:\n", str(matrix))


One-dimensional array: [1, 2, 4, 8, 16]
Two-dimensional array:
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 4  8 12 16]
 [ 8 16 24 32]]


## Linked List
Definition: _A collection of data elements called nodes which each contain a reference to the next node in the list._
- Elements can be easily inserted and removed.
- Underlying memory doesn't need to be reorganised.
- Can't do constant-time random item access.
- Item lookup is linear in time complexity (**O(n)**).

> Singly Linked List: Each data element links to the next element; Only one direction of traversal.

> Doubly Linked List: Each data element links to the next and previous elements; Two directions of traversal.

In [50]:
# Node class
class Node(object):
    def __init__(self, val):
        self.val = val
        self.next = None

    def get_data(self):
        return self.val

    def set_data(self, val):
        self.val = val

    def get_next(self):
        return self.next

    def set_next(self, next):
        self.next = next


# LinkedList class
class LinkedList(object):
    def __init__(self, head=None):
        self.head = head
        self.count = 0

    def get_count(self):
        return self.count

    def insert(self, data):
        # TODO: insert a new node
        new_node = Node(data)
        new_node.set_next(self.head)
        self.head = new_node
        self.count += 1

    def find(self, val):
        # TODO: find the first item with a given value
        item = self.head
        while (item != None):
            if item.get_data() == val:
                return item
            else:
                item = item.get_next()

        return None

    def deleteAt(self, idx):
        # TODO: delete an item at given index
        if idx > self.count-1:
            return
        if idx == 0:
            self.head = self.head.get_next()
        else:
            tempIdx = 0
            node = self.head
            while tempIdx < idx - 1:
                node = node.get_next()
                tempIdx += 1
            node.set_next(node.get_next().get_next())
            self.count -= 1

    def dump_list(self):
        tempnode = self.head
        while (tempnode != None):
            print("Node: ", tempnode.get_data())
            tempnode = tempnode.get_next()


# Create Linked List and insert items
itemlist = LinkedList()
itemlist.insert(38)
itemlist.insert(49)
itemlist.insert(13)
itemlist.insert(15)
itemlist.dump_list()

# Exercise the list
# print("Item count: ", itemlist.get_count())
# print("Finding item: ", itemlist.find(13))
# print("Finding item: ", itemlist.find(78))

# Delete an item
itemlist.deleteAt(3)
print("Item count: ", itemlist.get_count())
print("Finding item: ", itemlist.find(38))
itemlist.dump_list()


Node:  15
Node:  13
Node:  49
Node:  38
Item count:  3
Finding item:  None
Node:  15
Node:  13
Node:  49


## Stack
Definition: _A collection of data elements that supports **push** and **pop** operations._
- An element can be pushed (added) onto  the top of a stack.
- An element can be popped (removed) from the top of a stack.
- The last element pushed is the first element to be popped.
- Only the top (last) element on the stack can be popped at any given time.
> Works on _First In; Last Out (FILO)_ principle.

In [51]:
# TODO: create a new empty stack
stack = []

# TODO: push items onto the stack
stack.append(1)
stack.append(2)
stack.append(3)
stack.append(4)

# TODO: print the stack contents
print("Stack contents:", str(stack))

# TODO: pop an item off the stack
x = stack.pop()
print("Item popped:", str(x))
print("New stack contents:", str(stack))


Stack contents: [1, 2, 3, 4]
Item popped: 4
New stack contents: [1, 2, 3]


## Queue
Definition: _A collection of data elements that supports **adding** and **removing**._
- An element can be added to the end of the queue.
- An element can be removed from the front of the queue.
- The first element added is the first element to be removed.
- Only the first element in the queue can be removed at any given time.
> Works on _First In; First Out (FIFO)_ principle

In [52]:
from collections import deque

# TODO: create a new empty deque object that will function as a queue
queue = deque()

# TODO: add some items to the queue
queue.append(5)
queue.append(6)
queue.append(7)
queue.append(8)

# TODO: print the queue contents
print("Queue contents:", str(queue))

# TODO: pop an item off the front of the queue
x = queue.popleft()
print("Item removed:", str(x))
print("New quene contents:", str(queue))


Queue contents: deque([5, 6, 7, 8])
Item removed: 5
New quene contents: deque([6, 7, 8])


## Hash Table
Definition: _A collection of data elements which maps keys to their associated values._
- Uses the key in a hash function to compute an index into slots in hash table & map the key to the value.
- Key-to-value mappings are unique.
- Hash tables are typically very fast.
- For small datasets, arrays are usually more efficient.
- Hash tables don't order entries in a predictable way.

In [53]:
# TODO: create a hashtable all at once
items1 = dict({"a" : 1, "b" : "2", "c" : "three"})
print("Instantaneous hash table:", str(items1))

# TODO: create a hashtable progressively
items2 = {}
items2["d"] = 4
items2["e"] = "5"
items2["f"] = "six"
print("Progressive hash table:", str(items2))

# TODO: try to access a nonexistent key
# print("Non-existant key:", str(items1["z"]))

# TODO: replace an item
items2["e"] = "five"
print("Updated hash table:", str(items2))

# TODO: iterate the keys and values in the dictionary
for key, value in items2.items():
    print("Key", str(key) + ":", "Value:", str(value))


Instantaneous hash table: {'a': 1, 'b': '2', 'c': 'three'}
Progressive hash table: {'d': 4, 'e': '5', 'f': 'six'}
Updated hash table: {'d': 4, 'e': 'five', 'f': 'six'}
Key d: Value: 4
Key e: Value: five
Key f: Value: six


# Common Algorithms

## Euclid's Algorithm
Definition: _Find the greatest common denominator (GCD) of two integers._
>Example: GCD of 20 and 8 is 4 (Because 8/4 = 2 and 20/4 = 5)
1. For two integers _a_ and _b_, where _a > b_, divide _a_ by _b_.
2. If the remainder, _r_, is 0, then stop: GCD if _b_.
3. Otherwise, set _a_ to _b_, _b_ to _r_, and repeat at step 1 until _r_ is 0.

In [54]:
# Find the greatest common denominator of two numbers
# using Euclid's algorithm


def gcd(a, b):
    while (b != 0):
        t = a # store a temporarily
        a = b # set a to b
        b = t % b # set b to remainder of 
        
    return a

# Try out the function with a few examples
w = 60
x = 96
y = 20
z = 8

print("GCD of", str(w), "and", str(x) + ":", gcd(60, 96)) # should be 12
print("GCD of", str(y), "and", str(z) + ":", gcd(20,8)) # should be 4


GCD of 60 and 96: 12
GCD of 20 and 8: 4
